### ISSUE TITLE
Add scrolling gallery to home page

### ISSUE THREAD

**Issue by MrRa1n** [enucs/enucs#13]
Add a scrolling gallery of images with links to various pages/articles

**Comment by omonimus1** [comment]
Hi @MrRa1n ,I close this issue and contribute to the website if you like.
Would you like to add a [Carousel](https://getbootstrap.com/docs/4.0/components/carousel/) or just individual images or cards?

Do you have any mockups of the UX for the integration of this feature? 
If yes, Please share it here and will be happy to close this issue.
