### ISSUE TITLE
UPDATED README.md -> Add instructions on how to run the website locally

### ISSUE THREAD

**Issue by omonimus1** [enucs/enucs#35]
To help current and future students to manage and improve the enucs website, it will be extremely useful add a guide about how to run the website locally;

**Comment by glugg23** [comment]
Should be fixed by commit a204ed205bcc14d68f9d805f56cf6174b070a0b8, let me know if there are any questions you have with the new steps.

If you need some data to put in the database just tag me and I can show you how to backup our live data so you can import it.
